services:
  frontend:
    build:
      context: ./togal-front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    build:
      context: ./togal
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: host.docker.internal
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mdp
      POSTGRES_DB: togal
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
